# Generated by Django 4.0.6 on 2022-09-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariavelQualitativaNominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariavelQualitativaOrdinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariavelQuantitativaContinuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariavelQuantitativaDiscreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValorQuantitativoDiscreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BigIntegerField()),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelquantitativadiscreto')),
            ],
        ),
        migrations.CreateModel(
            name='ValorQuantitativoContinuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=30, max_digits=64)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelquantitativacontinuo')),
            ],
        ),
        migrations.CreateModel(
            name='ValorQualitativoOrdinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('ordem', models.IntegerField(null=True)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelqualitativaordinal')),
            ],
        ),
        migrations.CreateModel(
            name='ValorQualitativoNominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelqualitativanominal')),
            ],
        ),
        migrations.CreateModel(
            name='GraficoBarrasParaVariaveisQualitativasOrdinais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField()),
                ('ordem', models.IntegerField(null=True)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelqualitativaordinal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraficoBarrasParaVariaveisQualitativasNominais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField()),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelqualitativanominal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
