# Generated by Django 4.0.6 on 2022-08-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariavelQualitativoNominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariavelQualitativoOrdinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariavelQuantitativoContinuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariavelQuantitativoDiscreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=10000, verbose_name='descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValorQuantitativoDiscreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BigIntegerField()),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelquantitativodiscreto')),
            ],
        ),
        migrations.CreateModel(
            name='ValorQuantitativoContinuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=30, max_digits=64)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelquantitativocontinuo')),
            ],
        ),
        migrations.CreateModel(
            name='ValorQualitativoOrdinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('ordem', models.IntegerField()),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelqualitativonominal')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ValorQualitativoNominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estatistica.variavelqualitativonominal')),
            ],
        ),
    ]
