# Generated by Django 4.0.5 on 2022-06-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0001_alter_password_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='titulo',
            new_name='title',
        ),
    ]
