# Generated by Django 4.0.5 on 2022-06-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
