# Generated by Django 4.0.5 on 2022-06-26 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passwordManager', '0002_rename_titulo_password_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
