# Generated by Django 4.0.5 on 2022-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0002_password_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='titulo',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
