# Generated by Django 4.0.5 on 2022-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0003_password_user'),
    ]

    operations = [
        migrations.RunSQL(
            'UPDATE passwordManager_password'
            ' SET user_id = (SELECT au.id FROM auth_user AS au WHERE au.username = "yoshio.mori");'
        ),
    ]
