# Generated by Django 4.0.5 on 2022-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0003_alter_password_titulo'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE passwordManager_password "
            "SET titulo = id;"
        ),
    ]
